# Generated by Django 4.1.3 on 2022-11-25 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('task', models.TextField(verbose_name='Описание')),
                ('idate', models.DateField(verbose_name='дата заявки')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
        migrations.CreateModel(
            name='Сustomer_card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_input_card', models.DateField(verbose_name='Дата создания карточки')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилие')),
                ('name_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('first_name', models.CharField(max_length=50, verbose_name='Отчество')),
                ('place_of_issue', models.CharField(max_length=200, verbose_name='Место выдачи')),
                ('division_code', models.CharField(max_length=7, verbose_name='Код подразделения')),
                ('date_of_issue', models.DateField(verbose_name='Дата выдачи')),
                ('date_of_birth', models.DateField(verbose_name='Дата рождения')),
                ('place_of_birth', models.CharField(max_length=250, verbose_name='Место рождения')),
                ('registration_address', models.CharField(max_length=250, verbose_name='Адрес регистрации')),
                ('residential_address', models.CharField(max_length=250, verbose_name='Адрес проживания')),
                ('sn_passport', models.CharField(max_length=15, verbose_name='Серия и номер паспорта')),
                ('snils', models.CharField(max_length=14, verbose_name='Номер СНИЛС')),
            ],
            options={
                'verbose_name': 'Карточка заявителя',
                'verbose_name_plural': 'Карточки заявителей',
            },
        ),
    ]
